tomas-abrahamsson/gpb

src/gpb_compile.erl

```
src/delivery_info.erl:42: syntax error before: DeliveryInfo
```
```
42: -type 'DeliveryInfo'() :: #DeliveryInfo{}.
```
should be
```
42: -type 'DeliveryInfo'() :: #'DeliveryInfo'{}.
```

Fix records type declaration

---

src/gpb.erl
src/gpb_compile.erl

Bumped into this while running property tests for encode/decode equality. I compiled my proto files with `-strbin` option such that strings are returned as binaries. I was expecting to be able put binary strings in and get binary strings out but always get the `bad_unicode_strings` error. As far as I understand `unicode:characters_to_binary` is idempotent, so this change doesn't change any fundamentals. I couldn't quite find a spot to place a test but I'm open to add some if you would point me into the right direction.

Accept binary strings

---

helpers/package-for-hex.pm

`gpb` packages uploaded to hex.pm are broken. Their `gpb.app` files are missing a comma:
```
{application, gpb,
[{description, "Google protocol buffer compiler and runtime support"},
{vsn,"3.18.1"}
{modules, [gpb, gpb_compile, gpb_scan, gpb_parse, gpb_codegen]},
{applications, [kernel, stdlib]},
{registered, []},
{env, []}]}.
```
I couldn't test this because of the the proper version restrictions and I don't have Elixir installed. 
In the light of rebar3 being able to use pure Erlang packages from hex.pm I think it is definitely worth fixing this.

Fix `gpb.app` file generation for hex.pm

---

src/gpb_compile.erl

Just some fixes for the help text and comments.

Fix a few typos in help text and comments

---

src/gpb_parse.yrl
test/gpb_parse_tests.erl

The last two "issues" I found turned out to be my misunderstanding, but this time I think I have found something I can actually improve. I have a proto message that adds a nested message in an `extend` block. When I do this the `{ref, other_message}` does not get replaced with a `{msg, other_message}` during the `post_process_all_files/2` step.
It looks like there isn't a test case for this use case and when I added one it leaves the `{ref, other_message}`. Do you have any suggestions about how to tackle this one? I'm happy to contribute a fix here, just want to verify that this is an issue worth fixing first :smile:

add a test for extending a message with a nested message

---

src/gpb_compile.erl

Defaults in map specs are not supported by the Erlang compiler.

Don't put defaults for map specs

---

benchmarks/Makefile

* Use pkg-config if present to get protobuf lib information.
* Use `which` to find `protoc` command, else use `PROTOC` or `PROTOHOME`
* Pass `CXXFLAGS` to C++ compiler so that include path to `erl_nif.h` can be specified.
* Remove call to detect if lite lib should be used as the `LITE_RUNTIME` option is not present in `msg.proto`
Command used to compile using the system protobuf lib 2.6.1 (on Arch Linux):
```sh
git clean -fxd; make NIFS=1 CXXFLAGS='-I/home/erlang/installs/18.3-hipe/usr/include'
```
Command used to test using protobuf installed to`$HOME/opt/protobuf/3.0.0-beta-3`:
```sh
$ git clean -fxd; make NIFS=1 PROTOC="$HOME/opt/protobuf/3.0.0-beta-3/bin/protoc" PROTOBUF_CFLAGS="-I$HOME/opt/protobuf/3.0.0-beta-3/include" PROTOBUF_LDFLAGS="-L$HOME/opt/protobuf/3.0.0-beta-3/lib …
```

Small benchmark Makefile changes

---

README.md
src/gpb.erl
src/gpb_compile.erl
test/gpb_compile_tests.erl
test/gpb_parse_tests.erl
test/gpb_tests.erl

Accept 0 and 1 for false / true boolean values.
Related to #63 
Questions -
* These changes will also allow `0` and `1` as `default` values, which isn't part of the PB spec. This doesn't seem to be the end of the world, though. What do you think @tomas-abrahamsson ?
* Could you point me to the tests to show binary data being decoded to `true` and `false` atoms? I couldn't find them, and just wanted to verify.
Thanks!

Accept 0 and 1 as boolean values

---

src/gpb_compile.erl
test/gpb_compile_tests.erl

Adds `encode/1` and `decode/2` with same signature as what is used in `erlang_protobuffs`
See #63

Add functions for epb compatibility.

---

src/gpb.erl
src/gpb_compile.erl
test/gpb_compile_tests.erl

Another piece of `epb` compatibility.
See tomas-abrahamsson/gpb#63
TODO:

Allow lists as indata for bytes fields.

---

.gitignore
build/compile_descriptor
src/gpb_compile.erl
src/gpb_parse.yrl
test/gpb_compile_tests.erl
test/gpb_parse_tests.erl

This PR covers the issues: #73 #74 and #75 
In addition to adding `msg_name_to_snake_case`, `by_proto` and the fixes for oneof/maps this also has a few changes to make it work better with rebar3. Mainly moving the `compile_descriptor` hook to a `pre_hook` instead of `post`.

Snake case support, by_proto prefix, oneof/maps fix

---

src/gpb_parse.yrl
test/gpb_parse_tests.erl

Just ran into this issue with a map using a type that needs to be prefixed in the generate code.

fix use of by_proto on map types

---

bin/protoc-erl

When made a soft link of `protoc-erl`
(e.g. `ln -s PATH/gpb/bin/protoc-erl /usr/local/bin`,  to add `protoc-erl` in $PATH),
There will be an error occurred due to the wrong path.
So I add a link file check for handle this case.

Fix symbolic link error of `protoc-erl`

---

src/gpb_compile.erl

This fixes the sort of defs to take into account if a message has a map field that has a value type of another message.

include map value types in message topsort

---

src/gpb_parse.yrl
test/gpb_parse_tests.erl

As per [Custom Options](https://developers.google.com/protocol-buffers/docs/proto#options) in the Protobufs spec, this patch extends the parser in `gpb` to include the ability to specify custom option extensions.
E.g., we now allow:
```protobuf
import "google/protobuf/descriptor.proto";
extend google.protobuf.MessageOptions {
optional string my_option = 51234;
}
message MyMessage {
option (my_option) = "Hello world!";
}
```
and, more complexly:
```protobuf
service MyService {
option (my_service_option) = FOO;
rpc MyMethod(RequestType) returns(ResponseType) {
// Note:  my_method_option has type MyMessage.  We can set each field
//   within it using a separate "option" line.
option (my_method_option).foo = 567;
option (my_method_option).bar = "Some string";
}
}
```
I am relatively new to …

Extend parser to include Custom Options

---

README.md
src/gpb_compile.erl
test/gpb_compile_maps_tests.erl

When encoding/decoding as maps (and maps_unset_optional set to omitted), the merge message function clause should not treat repeated fields as
required.

Bugfix for erlang maps encoding/decoding when maps_unset_optional is set to omitted

---

src/gpb_parse.yrl

Useful with https://github.com/Bluehouse-Technology/grpc to have function names that don't require single quoting.

apply tolower or snakecase to rpc names as well

---

src/gpb_compile.erl
test/gpb_compile_maps_tests.erl
test/gpb_compile_tests.erl

Currently when generating using the proto3 syntax, `#foo{} =/= foo:decode(<<>>)`, which is kind of painful, especially when testing.  This PR makes it such that default fields are no longer undefined, but rather set to their type default, which should make them more like the output of decode.  Sub-messages are left as undefined; I'm not sure what the specification suggests, but I went with this behavior to match that of decode.

make default records fields and missing pb fields equivalent.

---

src/gpb_gen_introspect.erl

This fixes the following four Dialyzer errors, which started showing up once I upgraded gpb from 3.28.0 to 4.5.0 (Erlang/OTP 20.3.)
[...]: Function fqbin_to_service_name/1 only terminates with explicit exception
[...]: Function service_name_to_fqbin/1 only terminates with explicit exception
[...]: Function fqbins_to_service_and_rpc_name/2 only terminates with explicit exception
[...]: Function service_and_rpc_name_to_fqbins/2 only terminates with explicit exception
The errors are prevented by making single-clause definitions of said functions explicitly declare their return value type as `no_return()`.
The following is a screenshot of the errors as output by rebar3:

Fix Dialyzer errors when analyzing serviceless protocol code

---

src/gpb_gen_introspect.erl
src/gpb_gen_types.erl

Hi there,
always get following errors when running dialyzer checking, please kindly consider merging this PR. Thanks a lot.
> function fqbin_to_enum_name/1: at line 625: @spec name does not match.
> 68: Record construction #on_connect_r{connection_ref::binary()} violates the declared type of field connection_ref::'undefined' | maybe_improper_list(binary() | maybe_improper_list(any(),binary() | []) | byte(),binary() | [])

some spec issue fix

---

src/gpb_compile.erl

As explained at https://github.com/tomas-abrahamsson/gpb/issues/176, gpb looks
for a well known type directory provided in the private directory of the gpb
application. Infortunately, this directory is not always available, e.g. in
escripts, causing gpb_compile:file/1 to fail. Additionally, some users may
have reasons to provide their own well know type directory as a simple include
path.
We add the `ignore_wellknown_types_directory` compile option which can be used
to skip the check for the directory. Users are then free to provide the
include path of their choosing with the `i` option.
close #176

add an option to ignore the default well known type directory

---

src/gpb_gen_types.erl
test/gpb_compile_tests.erl

Closes #185
With the added test case, but without the fix in gpb_gen_types, the test fails with:
```
**error:{badmatch,{error,[{"gpb_compile_tests-tmp-1.erl",
[{71,erl_lint,{undefined_type,{'foo.bar.E1',0}}},
{71,erl_lint,{undefined_type,{'foo.bar.msg.E2',0}}}]}],
[{"gpb_compile_tests-tmp-1.erl",
[{69,erl_lint,{unused_type,{'foo.bar.e1',0}}},
{70,erl_lint,{unused_type,{'foo.bar.msg.e2',0}}}]}]}}
```

Apply renames to the enum type also in export_type

---

build/compile_descriptor

closes #204 
this appears to fix my compilation with elixir 1.12
~I'm a bit worried that this is just a band-aid fix of some other issue. I can't seem to hunt down what exactly changed in the elixir source that would cause this to be necessary~
it looks like rebar recently added support for this environment variable (see https://github.com/erlang/rebar3/pull/2237) which mix started passing to rebar in elixir 1.12

respect `REBAR_BARE_COMPILER_OUTPUT_DIR` env var during descriptor compilation

---

src/gpb.erl

Switches the internals of the `gpb` encoder to iolists. As mentioned in #217, this can improve the performance for larger payloads.
Since `gpb:encode_varint` is exported and it returns binary, I changed the internals of gbp to use `en_vi` instead, which returns an iolist. I'd probably rename this function to something like `encode_varint_iolist`.
Since some recursions were switched to tail, I also took the liberty of converting them to list comprehensions, which slightly simplified the code. The one that I didn't touch was `encode_2`, which could also be replaced by a comprehension, but I'm not completely that the code would be simpler in this case, so I left it as is.

encoder with iolists

---

README.md
priv/proto3/google/protobuf/any.proto
priv/proto3/google/protobuf/api.proto
priv/proto3/google/protobuf/descriptor.proto
priv/proto3/google/protobuf/duration.proto
priv/proto3/google/protobuf/empty.proto
priv/proto3/google/protobuf/field_mask.proto
priv/proto3/google/protobuf/source_context.proto
priv/proto3/google/protobuf/struct.proto
priv/proto3/google/protobuf/timestamp.proto
priv/proto3/google/protobuf/type.proto
priv/proto3/google/protobuf/wrappers.proto

I observed that the Google well-known proto types in this repository are currently fixed at version 3.12.3, which seems a bit outdated.
This pull request addresses this by updating the Protobufs file.

Update google wellknown protos

---

src/gpb_defs.erl

Found this while consuming the result of `gpb_parse:parse/1` on a file that contains an option.

fix: Improve on `gpb_defs`'s for possible result

---

src/gpb_gen_verifiers.erl
src/gpb_lib.erl
test/gpb_compile_maps_tests.erl

Previously, when using maps with binary keys, flat unions and verification, unions would not work, even with binary map keys as expected.
For example, with the following definitions:
```erlang
Src = """
syntax = "proto3";
message test {
map<string, string> args = 1;
}
message union {
oneof u {
int32 a = 1;
string b = 2;
}
}
""".
{ok, Mod, Bin} = gpb_compile:string(aaa, Src, [binary, strings_as_binaries, {maps, true}, {maps_oneof, flat}, {maps_key_type, binary}, {verify, always}, {maps_unset_optional, omitted}]).
code:load_binary(Mod, "aaa.erl", Bin).
```
... normal maps work as expected:
```erlang
7>   Encoded1 = Mod:encode_msg(#{<<"args">> => #{<<"hey">> => <<"hi">>}}, test).
<<10,9,10,3,104,101,121,18,2,104,105>>
8>   Mod:decode_msg(Encoded1, test).
#{<<"args">> => #{<<"hey">> => …
```

fix: support binary map keys in unions
